### ISSUE TITLE
"Could not compile mli file" error

### ISSUE THREAD

**Issue by anton-trunov** [QuickChick/QuickChick#179]
I tried stepping through https://github.com/QuickChick/QuickChick/blob/8.9/examples/Tutorial.v file, but `QuickChick removeP ` at [line 57](https://github.com/QuickChick/QuickChick/blob/3a23c7822c1c5b17ac65a42b00fa1823a46c4793/examples/Tutorial.v#L57) produces the following error message:

> Error: Could not compile mli file

I have QuickChick v1.1.0 and Coq 8.9.1 installed via opam.

**Comment by liyishuai** [comment]
I didn't replicate this error on my side.
Could you try `coq-quickchick.8.9.dev` (from extra-dev, or current 8.9 branch), and turn on `QuickChickDebug Debug On.` for more messages?

**Comment by Lysxia** [comment]
What's your OCaml version?

**Comment by anton-trunov** [comment]
More info on my opam installation: ocaml-base-compiler.4.07.1, coq-mathcomp-ssreflect v1.9.0.
Ok, `QuickChickDebug Debug On.` didn't give any extra info.
This error appears from within ProofGeneral, but not when I load the tutorial using `coqtop` (or `coqc) from command line.

**Comment by anton-trunov** [comment]
My `*coq*` buffer has the following
```
<prompt>Coq < 85 || 0 < </prompt>QuickChick removeP.
QuickChecking removeP
sh: ocamlopt: command not found
Toplevel input, characters 0-19:
> QuickChick removeP.
> ^^^^^^^^^^^^^^^^^^^
Error: Could not compile mli file
       

<prompt>Coq < 85 || 0 < </prompt>
```

It looks like `ocamlopt` compiler is not somehow in the path.

**Comment by SongChujun** [comment]
Did you solve the problem?

**Comment by anton-trunov** [comment]
Sorry, didn’t have time to look into this again

**Comment by SongChujun** [comment]
I partially resolved the problem. First, you need to make sure that you can compile Tutorial.v from the command line, then you can open emacs from the command line and see the result. That works for me.

BTW, what's the OS you use? If you use Mac, the reason I guess is that since the latest version of OS X Catalina has a very strict privacy policy, emacs has no access to the executable file ocamlopt, so it can't execute it. So I opened emacs from the command line so it can inherit the environment of the command line and it works!

**Comment by SongChujun** [comment]
And you may refer to this nice post:[https://emacs.stackexchange.com/questions/53026/how-to-restore-file-system-access-in-macos-catalina](url)

**Comment by anton-trunov** [comment]
I cannot reproduce my issue anymore, looks like it was something environment-related on my side. Sorry for the noise, closing this.
