### ISSUE TITLE
QuickChick writes results to stderr

### ISSUE THREAD

**Issue by jcoveney** [QuickChick/QuickChick#199]
Hello! I think this may be related to; https://github.com/QuickChick/QuickChick/issues/96

I am new to all of this, so forgive me if I say something mistaken/dumb.

Using Coqtail in vim, I couldn't see QuickChick output. I filed a bug with Coqtail, who is interested in making this work: https://github.com/whonore/Coqtail/issues/99

That said, it is unclear right now what is the "right" way. Right now, it seems like QuickChick is using stderr for this output, instead of using coqtop's XML api. Is that correct?

I think there are three possibilities:
1. This is how coqtop intends things to work. This seems unlikely to me, given there is an API, it seems undesirable for important output to just be kicked to stderr
2. coqtop has an API that QuickChick isn't using
3. coqtop lacks a proper way to handle this, and so QuickChick is forced to print to stderr

Is this accurate? If it is number 3 above, we can close this and I can file an issue against Coq.

**Comment by Lysxia** [comment]
I believe it's (2), there's an API and we just didn't get around to using it properly, but I don't really know anything about it personally. For anyone interested in fixing it, this I think is the relevant output line that needs fixing:

https://github.com/QuickChick/QuickChick/blob/120e155c32e443e82a16a871706942231f60bfea/src/quickChick.mlg#L180-L182

If you look around those lines, there are some uses of a `CError` module which indicates there's at least an API for error messages, that's why I think there's probably also one for regular info messages.

**Comment by Lysxia** [comment]
#200 should fix this.
